// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8aJaeEOyKhsF8skJTK6wxd5E3w1B5LTk',
    appId: '1:1005352044783:web:69504a0111180fb0b2731a',
    messagingSenderId: '1005352044783',
    projectId: 'instagram-clone-65ebb',
    authDomain: 'instagram-clone-65ebb.firebaseapp.com',
    storageBucket: 'instagram-clone-65ebb.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAW3O2bKZUYLBpmZRXt7MmaCKYD0y7QKKU',
    appId: '1:1005352044783:android:3f4300e2988b9b28b2731a',
    messagingSenderId: '1005352044783',
    projectId: 'instagram-clone-65ebb',
    storageBucket: 'instagram-clone-65ebb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmxZNYtgkGwXm-SjBedq5_QCij58lenOc',
    appId: '1:1005352044783:ios:6bb429f9c635d3eab2731a',
    messagingSenderId: '1005352044783',
    projectId: 'instagram-clone-65ebb',
    storageBucket: 'instagram-clone-65ebb.appspot.com',
    iosBundleId: 'com.example.instagramClone',
  );
}
